# ไฟล์นี้ใช้ตั้งค่าตัววิเคราะห์ซึ่งตรวจสอบโค้ด Dart แบบสแตติก
# เพื่อค้นหาข้อผิดพลาด คำเตือน และปัญหาตามกฎ lint
#
# ปัญหาที่ตัววิเคราะห์พบจะแสดงในส่วนติดต่อของ IDE ที่รองรับ Dart
# (https://dart.dev/tools#ides-and-editors) และสามารถเรียกตัววิเคราะห์
# ผ่านบรรทัดคำสั่งด้วย `flutter analyze`

# บรรทัดต่อไปนี้เปิดใช้ชุดกฎ lint ที่แนะนำสำหรับแอป Flutter
# แพ็กเกจ และปลั๊กอิน เพื่อส่งเสริมแนวทางการเขียนโค้ดที่ดี
include: package:flutter_lints/flutter.yaml

linter:
  # สามารถปรับแต่งกฎ lint ของโปรเจกต์ได้ในส่วนด้านล่าง
  # โดยปิดกฎจาก `package:flutter_lints/flutter.yaml` ที่รวมไว้ด้านบน
  # หรือเปิดใช้กฎเพิ่มเติม รายการกฎและเอกสารทั้งหมดอยู่ที่
  # https://dart.dev/lints
  #
  # นอกจากปิดกฎ lint สำหรับทั้งโปรเจกต์ในส่วนด้านล่างแล้ว
  # ยังสามารถระงับกฎเฉพาะบรรทัดหรือเฉพาะไฟล์ Dart ได้ด้วยรูปแบบ
  # `// ignore: name_of_lint` และ `// ignore_for_file: name_of_lint`
  # ในบรรทัดหรือไฟล์ที่ทำให้เกิดคำเตือน
  rules:
    # avoid_print: false # ยกเลิก comment เพื่อปิดกฎ `avoid_print`
    # prefer_single_quotes: true # ยกเลิก comment เพื่อเปิดกฎ `prefer_single_quotes`

# ดูข้อมูลเพิ่มเติมเกี่ยวกับไฟล์นี้ได้ที่
# https://dart.dev/guides/language/analysis-options
